name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '13.x'
        registry-url: https://registry.npmjs.com/
        scope: '@sergioramos'
    - name: Install dependencies
      run: yarn install --immutable
      env:
        YARN_CHECKSUM_BEHAVIOR: update
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
